import { ZERO } from "../util/constants";

const ACCEPTANCE_NONE = ZERO;
const ACCEPTANCE_TAB_DAY = 34;
const ACCEPTANCE_COMPOSER_DAY = 86.7;
const STREAK_SINGLE_DAY = 1;
const STREAK_THREE_DAYS = 3;
const BUSIEST_TAB_LOW = 10;
const BUSIEST_TAB_HIGH = 264;
const BUSIEST_TAB_MID = 5;
const BUSIEST_COMPOSER_ONLY = 999;
const BUSIEST_TOTAL_LOW = 10;
const BUSIEST_TOTAL_HIGH = 264;
const BUSIEST_TOTAL_COMPOSER = 1004;
const MERGE_DAY_ONE_COMPOSER = 150;
const MERGE_DAY_ONE_TAB = 15;
const MERGE_DAY_ONE_TOTAL = 165;
const MERGE_DAY_TWO_COMPOSER = 20;
const MERGE_DAY_TWO_TAB = 40;
const MERGE_DAY_TWO_TOTAL = 60;
const METRICS_ACCEPTED_TEN = 10;
const METRICS_SUGGESTED_ZERO = ZERO;
const METRICS_ACCEPTED_THIRTY_FOUR = 34;
const METRICS_SUGGESTED_HUNDRED = 100;
const METRICS_ACCEPTED_SIX_OH_SEVEN = 607;
const METRICS_SUGGESTED_SEVEN_HUNDRED = 700;
const STREAK_ACTIVITY_ONE = 1;
const STREAK_ACTIVITY_TWO = 2;
const STREAK_ACTIVITY_THREE = 3;

export {
    ACCEPTANCE_COMPOSER_DAY,
    ACCEPTANCE_NONE,
    ACCEPTANCE_TAB_DAY,
    BUSIEST_COMPOSER_ONLY,
    BUSIEST_TAB_HIGH,
    BUSIEST_TAB_LOW,
    BUSIEST_TAB_MID,
    BUSIEST_TOTAL_COMPOSER,
    BUSIEST_TOTAL_HIGH,
    BUSIEST_TOTAL_LOW,
    MERGE_DAY_ONE_COMPOSER,
    MERGE_DAY_ONE_TAB,
    MERGE_DAY_ONE_TOTAL,
    MERGE_DAY_TWO_COMPOSER,
    MERGE_DAY_TWO_TAB,
    MERGE_DAY_TWO_TOTAL,
    METRICS_ACCEPTED_SIX_OH_SEVEN,
    METRICS_ACCEPTED_TEN,
    METRICS_ACCEPTED_THIRTY_FOUR,
    METRICS_SUGGESTED_HUNDRED,
    METRICS_SUGGESTED_SEVEN_HUNDRED,
    METRICS_SUGGESTED_ZERO,
    STREAK_ACTIVITY_ONE,
    STREAK_ACTIVITY_THREE,
    STREAK_ACTIVITY_TWO,
    STREAK_SINGLE_DAY,
    STREAK_THREE_DAYS,
};
