// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Sync from '../src/commands/sync.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['sync'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'sync': Sync
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'sync': {
      name: 'sync',
      description: 'Sync Cursor stats from the local database to the output directory',
      options: {
        'outputDir': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Directory for stats.json and machines/*.json (default: current working directory)', short: 'o', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'push': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Commit and push the generated files to the git remote', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3098,"end":3103,"loc":{"start":{"line":85,"column":41,"index":3098},"end":{"line":85,"column":46,"index":3103}},"value":false}}]}, validator: '(val) => true' },
        'show-composer': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Show the composer metric (hide with --show-composer false)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3312,"end":3316,"loc":{"start":{"line":90,"column":52,"index":3312},"end":{"line":90,"column":56,"index":3316}},"value":true}}]}, validator: '(val) => true' },
        'show-tab': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Show the tab metric (hide with --show-tab false)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3501,"end":3505,"loc":{"start":{"line":94,"column":47,"index":3501},"end":{"line":94,"column":51,"index":3505}},"value":true}}]}, validator: '(val) => true' },
        'vscdb': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Path to state.vscdb (default: platform Cursor database path)', short: 'd', fileType: 'path', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/sync'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
